---
title: "Power analysis for Smith replication experiments"
author: "Jon Bakdash and Laura Cooper"
date: "10/20/2021"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE, tidy = FALSE)
options(width = 100)

#Get the working directory
  workingdir <- getwd()
  
  
if(!require("pacman")) install.packages("pacman")

pacman::p_load(knitr, rmarkdown, yaml, tidyverse, Superpower, 
               parallel, optimParallel, ez, psychReport, sjstats, rstatix,
               corrplot)

#Save renv lock file
#renv::snapshot()

#Superpower isn't multithreaded, but mkl likely still provides a boost
#Set number of cpus to the number of cores 
  #num.cpus <- parallel::detectCores(logical = T)
  #options(boot.ncpus = num.cpus)

#Number of cores R is using
  #getOption("boot.ncpus", 1L)
  
sessionInfo()
```

### Effective sample size with replicated measures
Goulet, M.-A., & Cousineau, D. (2019). The Power of Replicated Measures 
to Increase Statistical Power. Advances in Methods and Practices in 
Psychological Science, 2(3), 199–213. https://doi.org/10/gf5swn
```{r}
r.from.alpha <- function(alpha.val, # Cronbach's alpha 
                         m.val)# Number of replications per participant, per cell
  {
  r.val <-  1/(1 + (m.val*(1/alpha.val - 1))) 
  return(r.val)
  }

#Assuming a high Cronbach's alpha, conservative estimate for sample size gain
 exp1.r <- r.from.alpha(0.85, 48) #288 total trials, 6 cells = 48 trials per cell
 exp2.r <- r.from.alpha(0.85, 48) #48 test trials per block, 8 block, and 8 cells
 exp3.r <- r.from.alpha(0.85, 64) #64 trials per block, 4 blocks, and 4 cells

n1.eff.sample <- function(nm,  #Total sample size
                          m.val,
                          r.val
                          ) 
  {
  n1 <- ((nm - 1)*m.val)/(1 + (m.val - 1)*r.val) + 1
  return(n1)
  }

#Effective sample sizes
#N = 50 for each experiment 
exp1.eff.N <- n1.eff.sample(50, 48, exp1.r)
exp1.eff.N


exp2.eff.N <- n1.eff.sample(50, 48, exp2.r)
exp2.eff.N

    
exp3.eff.N <- n1.eff.sample(50, 64, exp1.r)
exp3.eff.N

#Sample size gain multiplier with replicated trials
  exp1.eff.N/50
  exp2.eff.N/50
  exp3.eff.N/50
    
#Rounded (whole number) effective sample sizes
  exp1.reff.N <- round(exp1.eff.N, digits = 0)
  exp1.reff.N
  
  exp2.reff.N <- round(exp2.eff.N, digits = 0)
  exp2.reff.N
  
  exp3.reff.N <- round(exp3.eff.N, digits = 0)
  exp3.reff.N
```

## Power analysis for effect sizes of interest
```{r}
#From Smith Excel sheet
#Exp 1: RT
exp1.means <- c(376.005, 391.367857, 375.726428, 383.347857, 382.5107143, 
                382.8871429)

exp1.SDs   <- c(62.01257388,	73.28657807,	69.71743768,	65.24234116,	
                62.97572102,	61.65609988)

exp1.labels <- c("posture", "sit", "stand", 
                 "congruency", "neut", "incon", "con")

#Check to see if neutral dropped for the Posture x Congruency interaction? 
  #F(2, 26)
  #Source: Howell, Fundamental Statistics for Behavioral Science 4th Edition 
  # Numerator 
  # (A - 1) x (B - 1)
  # (2 - 1)*(3 - 1)
  
  # Denominator
  # (A - 1) x (B - 1) x (N - 1) 
  # A = Posture, 2 levels
  # B = Congruency, 3 levels? 
  # N = Sample size, 14 participants
  
  #(Posture: 2 - 1) x (Congruency: 3 - 1) x (Sample Size: 14 - 1)
  # (2 - 1)*(3 - 1)*(14 - 1)
  # Appears to includes neutral, based on df in the interaction

#Load means from 3 Smith experiments
Smith_exp1_RT <- read.csv(paste0(workingdir, "/Smith_exp1_RT.csv"))
  head(Smith_exp1_RT)

Smith_exp2_acc <- read.csv(paste0(workingdir, "/Smith_exp2_acc.csv")) 
  head(Smith_exp2_acc)
  
Smith_exp3_RT <- read.csv(paste0(workingdir, "/Smith_exp3_RT.csv")) 
  head(Smith_exp3_RT)  
  
#Create correlation matrices for design_fct  
#Exp 1
  M1 <- cor(Smith_exp1_RT[,2:7])
  corrplot(M1)

#Exp 2
  M2 <- cor(Smith_exp2_acc[,2:9])
   corrplot(M2)
  
#Exp 3
  M3 <- cor(Smith_exp3_RT[,2:5]) #Not using slopes (last two columns)
   corrplot(M3)
    

  
# Smith_exp1_RT_narrow <- gather(Smith_exp1_RT,
#                                subj,
#                                RT,
#                                sit_neut:sit_con,
#                                sta_neut:sta_con)
# 
# Smith_exp1_RT_narrow$condition<- rep(
#                                     c(rep("neut", times = 14),
#                                       rep("incon", times = 14),
#                                       rep("con", times = 14)
#                                       ), 
#                                     times = 2
#                                     )
# 
# Smith_exp1_RT_narrow$posture <- c(rep("Sit", times = 42),
#                                   rep("Stand", times = 42))
# Smith_exp1_RT_narrow$subj <- as.factor(Smith_exp1_RT_narrow$subj)
# Smith_exp1_RT_narrow$condition <- as.factor(Smith_exp1_RT_narrow$condition)
# Smith_exp1_RT_narrow$posture <- as.factor(Smith_exp1_RT_narrow$posture)
# Smith_exp1_RT_narrow$subj = rep(Smith_exp1_RT$subj, times = 6)
#                     
# head(Smith_exp1_RT_narrow)           
# 
# exp1_anova <- ezANOVA(Smith_exp1_RT_narrow, 
#                       dv = RT, 
#                       wid = subj, 
#                       within = .(posture, condition), 
#                       type = 3, 
#                       detailed = TRUE,
#                       return_aov=F
#                       )
# 
# exp1_anova
# exp1_anova$ANOVA
# 
# # Partial eta-squared    #Effect                   Error
# exp1_anova$ANOVA$SSn[4]/(exp1_anova$ANOVA$SSd[4] + exp1_anova$ANOVA$SSn[4])
# 
# # Generalized eta-squared  #Sum squares all effects, NO error      
# exp1_anova$ANOVA$SSn[4]/sum(exp1_anova$ANOVA$SSd[1:4])
# 
# # Eta-squared               #Total sum squares 
# sum(exp1_anova$ANOVA$SSn[1])/sum(exp1_anova$ANOVA$SSd[1:4])
# 
# #Partial eta-squared is 0.27, same as reported
# aovEffectSize(exp1_anova, effectSize = "pes")
# #0.266663800
# 
# aovEffectSize(exp1_anova, effectSize = "ges")
# #* 0.0035565930
# 
# my.aov1 <- anova_test(
#                      Smith_exp1_RT_narrow,
#                      dv = RT,
#                      wid = subj,
#                      within = c(condition, posture)
#                      )
# 
# #3-way rm ANOVA in R using aov()
# my.aov <- aov(RT ~  posture * condition + Error((subj)/(posture*condition)),
#               Smith_exp1_RT_narrow)
# 
# summary(my.aov)
# anova_stats(my.aov)

#3 posture:congruency 2, 788 2188.35 7.81 *** .019   <.001
#          anova_posture:congruency  95.4    0.021165

# 
# 
# exp1.anova <- aov_ez("subj", "RT", Smith_exp1_RT_narrow,
#                      within = c("condition", "posture"), 
#                      type = 3)


#Exp 2: Accuracy  
exp2.means <- c(0.97039395,	0.93738492,	0.92253851,	0.83707885,	
                0.96995475,	0.95278776,	0.92968805,	0.87189628)

exp2.SDs   <- c(0.03458640,	0.05457752,	0.05131776,	0.09717051,	0.02519055,	
                0.03545601,	0.04419698,	0.06410994)

exp2.labels <- c("posture", "sit", "stand", 
                 "congruency", "con", "incon", 
                 "condition", "no_switch", "switch")
#Exp 3: RT
exp3.means <- c(548.905,	617.8666667,	567.75,	612.4383333)
exp3.SDs   <- c(99.22788982,	109.5684515,	119.3201426,	127.286163)

exp3.labels <- c("posture", "stand", "sit", 
                 "setsize", "four_items", "eight_items")



#Sensitivity analysis for power: Effect sizes of interest, including the min
  #Increasing SDs is more noise, thus lower effect sizes 
  SD.mulitplier <- c(1, 1.5, 2, 2.5, 3)

#Design output from ANOVA_design()
  design.exp1 <- list()
  design.exp2 <- list()
  design.exp3 <- list()

#Setup design for ANOVA_design, loop the length of the SD.multiplier 
design_fct <- function(factors, n, mu, sd, labelnames, corr.matrix, design.name) 
  {
    for (i in 1:length(SD.mulitplier)) {
      design.name[[i]] <- ANOVA_design(design = factors,
                                       n = n, #Effective sample size
                                       mu = mu, 
                                       sd = sd*SD.mulitplier[i],
                                       r <- corr.matrix,
                                       labelnames = labelnames,
                                       plot = FALSE)
                    }
return(design.name)
  }


#Exp 1
  exp1.design <- design_fct("2w*3w", 
                            exp1.reff.N,
                            exp1.means,
                            exp1.SDs,
                            exp1.labels,
                            M1, 
                            design.exp1)

#Exp 2 
  exp2.design <- design_fct("2w*2w*2w", 
                            exp2.reff.N,
                            exp2.means,
                            exp2.SDs,
                            exp2.labels,
                            M2,
                            design.exp2)
  

#Exp 3 
  exp3.design <- design_fct("2w*2w", 
                            exp3.reff.N,
                            exp3.means,
                            exp3.SDs,
                            exp3.labels,
                            M3, 
                            design.exp3)



#Setup for ANOVA_power() fct
#Seeds for reproducibility
  set.seed(432)
  exp1.seeds <- sample.int(1000, length(SD.mulitplier)) 
  
  set.seed(653)
  exp2.seeds <- sample.int(1000, length(SD.mulitplier)) 
  
  set.seed(797)
  exp3.seeds <- sample.int(1000, length(SD.mulitplier)) 

#Number of simulations
  nsims = 1000


power_result_exp1 <- list() #Row 3
power_result_exp2 <- list() #Row 5
power_result_exp3 <- list() #Row 2

#Code for testing
# 
# power_result_vig1 <- ANOVA_exact(exp2.design[[1]],
#                                  alpha = 0.05,
#                                  verbose = TRUE)
# power_result_vig1$aov_result
#  
# power_result_vig2 <- ANOVA_power(exp2.design[[1]],
#                                  alpha = 0.05,
#                                  nsims = nsims,
#                                  verbose = TRUE)
#  power_result_vig2
 
 
 
 #power_result_vig$aov_result
 #power_result_vig$main_results
 
# plot(exp1.design[[1]])

power_exp <- function(design, 
                      seed, 
                      row.to.extract,
                      output) 
  {
  for (i in 1:length(SD.mulitplier)) {
          power_result_vig <- ANOVA_power(design[[i]], 
                                          alpha = 0.05, 
                                          nsims = nsims, 
                                          seed = seed[i])
          output[[i]] <- power_result_vig$main_results[row.to.extract,]
                }
      return(output)
  }

exp1.power <- power_exp(exp1.design, exp1.seeds, 3, power_result_exp1)

exp2.power <- power_exp(exp2.design, exp2.seeds, 5, power_result_exp2)

exp3.power <- power_exp(exp3.design, exp3.seeds, 3, power_result_exp3)

#Convert lists to data frames
exp1.df <- do.call(rbind.data.frame, exp1.power)
exp2.df <- do.call(rbind.data.frame, exp2.power)
exp3.df <- do.call(rbind.data.frame, exp3.power)

#Create experiment variables
exp1.rep <- rep("Exp1", times = dim(exp1.df)[1])
exp2.rep <- rep("Exp2", times = dim(exp2.df)[1])
exp3.rep <- rep("Exp3", times = dim(exp3.df)[1])

#Add column with exp to each data frame
exp1.df <- cbind(exp1.rep, exp1.df)
exp2.df <- cbind(exp2.rep, exp2.df)
exp3.df <- cbind(exp3.rep, exp3.df)

#Rename first column to Experiment
colnames(exp1.df)[1] <- "Experiment"
colnames(exp2.df)[1] <- "Experiment"
colnames(exp3.df)[1] <- "Experiment"

#Print the data frames
print(exp1.df, row.names = F)
print(exp2.df, row.names = F)
print(exp3.df, row.names = F)

#Write power analysis for each exp as csv files
#**Note power is rounded to 100%, since this is a finite sample size it's
#*effectively perfect power but actually ~99.99%
write.csv(exp1.df, "exp1.csv", row.names = F)
write.csv(exp2.df, "exp2.csv", row.names = F)
write.csv(exp3.df, "exp3.csv", row.names = F)

#Original effect sizes as-reported in Smith
  exp1.eta2p <- 0.27 #Posture x Congruency interaction for RT
  exp2.eta2p <- 0.16 #Condition x Posture interaction for acc
  exp3.eta2p <- 0.35 #Posture x Set size interaction for RT
  
#Percent of lowest effect in power given original effect
  #Exp 1: 14.06%
  exp1.df[5,3]/exp1.eta2p

  #Exp 2: 15.80%
  exp2.df[5,3]/exp2.eta2p
  
  #Exp 3: 15.31%
  exp3.df[5,3]/exp3.eta2p

#Mean power for lowest effect
  #Exp 1-3
  sum(exp1.df[5,2], 
      exp2.df[5,2], 
      exp3.df[5,2])/3
  #95.23% power for Exp 1-3 
  
  #Exp 2-3
  sum(exp2.df[5,2], 
      exp3.df[5,2])/2
  #92.85% power for Exp 2 and 3
    
```

