---
title: "Task Switching Replication"
author: "Laura Marusich and Jon Bakdash"
date: "`r Sys.Date()`"
output:
  pdf_document: 
    latex_engine: xelatex
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = FALSE)
options(width = 100)


if(!require("pacman")) install.packages("pacman")
pacman::p_load(knitr, rmarkdown, yaml, bookdown, cowplot, pals, viridis, renv, 
               tidyverse, parallel, optimParallel, ez, psychReport, sjstats, 
               rstatix, corrplot, superb, apaTables, afex, readxl, rlang,
               ggstance, trimr)

devtools::install_github("JimGrange/trimr")
library(trimr)

#Create plots and tables directory 
dir.create(file.path(getwd(),"/plots"),  showWarnings = F)
dir.create(file.path(getwd(),"/output"),  showWarnings = F)

#Get the working directory
workingdir <- getwd()

#Kludge so ggforestplot doesn't need to be installed, b/c it requires devtools 
source(paste0(workingdir, "/fcts/theme_forest.R"))
source(paste0(workingdir, "/fcts/ng_colours.R"))
source(paste0(workingdir, "/fcts/geom_effect.R"))

#Modified version of forestplot from ggforestplot
#This modded version is from: https://osf.io/bxpjc/
source(paste0(workingdir, "/fcts/mod.forestplot.R"))

#get trimming function
source(paste0(workingdir, "/trimming/pjTrimmingV2.R"))
```



# Read in and Check Raw Data
```{r}
#Import current data
task_switching_raw <- read.csv(paste0(workingdir,
                                      "/Data/task-switching-replication-recoded-2.csv"))
head(task_switching_raw)

#does every person have 392 trials?
ntrials_sub <- task_switching_raw %>% 
  group_by(participant) %>%
  summarize(ntrials = n()) %>%
  pull(ntrials)

all(ntrials_sub == 392)

#does every block start with a buffer and have 49 trials?
task_switching_raw <- task_switching_raw %>%
  mutate(condblock = paste0(posture, blockNum))

blocktrials <- task_switching_raw %>%
  group_by(participant, condblock) %>%
  summarize(ntrials = n(), firsttrial = first(switchTrialType)) 

all(blocktrials$ntrials == 49)
all(blocktrials$firsttrial == "buffer")
```

# Clean Data
```{r}
#Drop buffer trials
task_switching_raw2 <- task_switching_raw %>% 
  filter(switchTrialType != "buffer")

#Recode Correct to 1 and Incorrect to 0
task_switching_raw2$correct_bin <- recode(task_switching_raw2$correct, 
                                          "no"  = 0,
                                          "yes" = 1)

#Calc overall acc by participant
ts_overall_acc <- task_switching_raw2 %>%
  group_by(participant)  %>%
  summarize(Accuracy    = mean(correct_bin))

#find participants with less than 80% accuracy
#2, 8, 15, 44, 49, 51
#First exclusion criteria
low_acc_subs <- ts_overall_acc %>% filter(Accuracy < 0.80) %>%
  pull(participant)


task_switching_raw3 <- task_switching_raw2 %>% 
  filter(!(participant %in% low_acc_subs))

#Calc mean Acc by participant and conditions (posture, con, switch)  
#Narrow format 
ts_acc_mean <- task_switching_raw3 %>%
  group_by(participant, 
           posture,
           congruentTrialType, 
           switchTrialType) %>%
  summarize(Accuracy    = mean(correct_bin))

#Convert data to wide format (for statview/SPSS/etc) 
ts_acc_mean_wide <- ts_acc_mean %>%
  pivot_wider(names_from = c(posture, 
                             congruentTrialType,
                             switchTrialType), 
              values_from =   Accuracy)

write.csv(ts_acc_mean_wide, file = "output/new_recoded_for_statview.csv", row.names = F)

ts_acc_mean <- data.frame(ts_acc_mean)
ts_acc_mean$posture <- as.factor(ts_acc_mean$posture)
ts_acc_mean$participant <- as.factor(ts_acc_mean$participant)
ts_acc_mean$congruentTrialType <- as.factor(ts_acc_mean$congruentTrialType)
ts_acc_mean$switchTrialType <- as.factor(ts_acc_mean$switchTrialType)
str(ts_acc_mean)

#Total N = 51 (6 dropped for total acc < 80%)
length(unique(ts_acc_mean$participant))

```


# Summarize Demographics
```{r}
demo_raw <- read.csv(paste0(workingdir, "/Data/Task Switching_February 24, 2022_13.05.csv"),
                     skip = 1) %>%
  slice(-1) %>%
  select(-c(Response.Type,IP.Address, Recipient.Last.Name:Distribution.Channel))
colnames(demo_raw)[10:15] <- c("Gender.Pick", "Gender.Text","Age","Race.Pick","Race.Text","Eng.First")

dim(demo_raw)
#59 records
#first two are test data
# need to match up the 6 dropped participants from behavioral data
demo_df <- demo_raw %>% 
  filter(!(X %in% c("test", low_acc_subs)))
dim(demo_df)

demo_df <- demo_df %>%
  mutate(Gender.New = ifelse(Gender.Pick %in% c("Man","Woman"), Gender.Pick, Gender.Text),
         Eng.First = toupper(Eng.First))

#gender breakdown
gender_table <- demo_df %>%
  group_by(Gender.New) %>%
  summarize(n = n())
gender_table

#age breakdown
hist(as.numeric(demo_df$Age),
     main = "Histogram of Participant Ages",
     xlab = "Participant Age")
age_table <- demo_df %>%
  group_by(Age) %>%
  summarize(n = n())
age_table

#age mean and sd
mean_age <- mean(as.numeric(demo_df$Age))
sd_age <- sd(as.numeric(demo_df$Age))

kable(matrix(c(mean_age, sd_age), nrow = 1), col.names = c("Mean of Age", "SD of Age"))

#race breakdown
race_table <- demo_df %>%
  group_by(Race.Pick) %>%
  summarize(n = n()) %>%
  arrange(desc(n))
race_table

#language breakdown
lang_table <- demo_df %>%
  group_by(Eng.First) %>%
  summarize(n=n())
lang_table


```


# Plots and Analyses 
## Accuracy
```{r, echo = TRUE}
#Accuracy by participant, before drops
hist(ts_overall_acc$Accuracy)

#Accuracy for all cells
hist(ts_acc_mean$Accuracy)

exp1_anova <- ezANOVA(ts_acc_mean, 
                      dv = Accuracy, 
                      wid = participant, 
                      within = .(posture, congruentTrialType, switchTrialType), 
                      type = 3, 
                      detailed = TRUE,
                      return_aov = T
)

exp1_anova2 <- aov_ez(data = ts_acc_mean, 
                      dv = "Accuracy", 
                      id = "participant", 
                      within = c("posture", "congruentTrialType", "switchTrialType"), 
                      type = 3, 
                      anova_table = list(es = "pes")
)

exp1_stats <- ezStats(ts_acc_mean, 
                      dv = Accuracy, 
                      wid = participant, 
                      within = .(posture, congruentTrialType, switchTrialType), 
                      type = 3
)
write.csv(exp1_stats[ ,-7], file = "output/Task_Switching_Descriptives_ACC.csv", row.names = F)

#data.frame(exp1_anova$ANOVA)
output_acc <- aovEffectSize(exp1_anova, effectSize = "pes")
output_acc <- data.frame(output_acc$ANOVA) %>%
  mutate(MSE = c(NA, exp1_anova2$anova_table$MSE), .before = F)
write.csv(output_acc, "output/Task_switching_ANOVA_acc.csv")
output_acc

#Calculate confidence interval: PES for posture x switch/condition interaction
#using ANOVA results            (partial eta-squared)
interaction_effect_CI <-
  get.ci.partial.eta.squared(exp1_anova$ANOVA$F[6], 
                             exp1_anova$ANOVA$DFn[6],
                             exp1_anova$ANOVA$DFd[6],
                             conf.level = 0.90) #90% CI is the  convention for PES
interaction_effect_CI

congruent.labs <- c("Congruent", "Incongruent")
names(congruent.labs) <- c("1", "2")

#make plot like Smith et al's
acc_plot <-
  superbPlot(ts_acc_mean_wide,
             WSFactors = c("Condition(2)", "Congruent(2)", "Posture(2)"),
             variables = colnames(ts_acc_mean_wide)[2:9],
             errorbar = "SE", #Tempted to change to CI, should stay SE to be consistent with SMith
             plotStyle = "line",
             factorOrder = c("Condition","Posture","Congruent"),
             adjustments = list(purpose = "difference"))+
  theme_classic() +
  ylim(0.77, 1) + #Trying to make ylim same as the Smith w/o cutting off error bars
  facet_wrap(vars(Congruent), labeller = labeller(Congruent = congruent.labs)) +
  scale_x_discrete(labels=c("1" = "No Switch", "2" = "Switch"))+
  scale_color_manual(values=c("#E69F00", "#0072B2"), 
                     labels = c("Sitting", "Standing")) +
  labs(y = "Accuracy")


ggsave(acc_plot, 
       file = "plots/acc_plot.pdf", 
       units = "in",
       width = 6.62, 
       height = 5.50,
       dpi = 600)

acc_plot
```

## RT for correct trials only 
```{r}
#look at reaction time for correct trials?
ts_correct_only <- task_switching_raw3 %>%
  filter(correct_bin == 1)

ts_rt_mean <- ts_correct_only %>%
  group_by(participant, 
           posture,
           congruentTrialType, 
           switchTrialType) %>%
  summarize(mean_rt    = mean(reactionTime))

#Convert data to wide format 
ts_rt_mean_wide <- ts_rt_mean %>%
  pivot_wider(names_from = c(posture, 
                             congruentTrialType,
                             switchTrialType), 
              values_from =   mean_rt)

RT_plot <- 
  superbPlot(ts_rt_mean_wide,
             WSFactors = c("Condition(2)", "Congruent(2)", "Posture(2)"),
             variables = colnames(ts_acc_mean_wide)[2:9],
             errorbar = "SE",
             plotStyle = "line",
             factorOrder = c("Condition","Posture","Congruent"),
             adjustments = list(purpose = "difference"))+
  theme_classic()+
  facet_wrap(vars(Congruent), labeller = labeller(Congruent = congruent.labs)) +
  scale_x_discrete(labels=c("1" = "No Switch", "2" = "Switch")) +
  scale_color_manual(values=c("#E69F00", "#0072B2"), labels = c("Sitting", "Standing")) +
  ylim(0.50, 0.70) +
  labs(y = "Reaction Time (seconds)")


ggsave(RT_plot, 
       file = "plots/RT_plot.pdf", 
       units = "in",
       width = 6.62, 
       height = 5.50,
       dpi = 600)

RT_plot

exp1_anova_rt <- ezANOVA(ts_rt_mean, 
                         dv = mean_rt, 
                         wid = participant, 
                         within = .(posture, congruentTrialType, switchTrialType), 
                         type = 3, 
                         detailed = TRUE,
                         return_aov = T
)

exp1_anova_rt2 <- aov_ez(data = ts_rt_mean, 
                         dv = 'mean_rt', 
                         id = 'participant', 
                         within = c('posture', 'congruentTrialType', 'switchTrialType'), 
                         type = 3
)

exp1_stats_rt <- ezStats(ts_rt_mean, 
                         dv = mean_rt, 
                         wid = participant, 
                         within = .(posture, congruentTrialType, switchTrialType), 
                         type = 3
)
write.csv(exp1_stats_rt[ ,-7], 
          file = "output/Task_Switching_Descriptives_RT.csv", row.names = F)

#data.frame(exp1_anova$ANOVA)
output_rt <- aovEffectSize(exp1_anova_rt, effectSize = "pes")
output_rt <- data.frame(output_rt$ANOVA) %>%
  mutate(MSE = c(NA, exp1_anova_rt2$anova_table$MSE), .before = F)
write.csv(output_rt, "output/Task_switching_ANOVA_RT.csv")
output_rt
```

## Generate RT analysis/plots for trimmed data
```{r}
#Second exclusion criteria (should this be moved up?)
#How many trials faster than 100 ms? Only a single one
sum(ts_correct_only$reactionTime < 0.100)
dim(ts_correct_only)

too.fast.gone <- ts_correct_only %>% filter(reactionTime >= 0.100) 
#Sanity check, one trial is dropped. Now have 17,698 trials
dim(too.fast.gone)

#perhaps double check trimmed output with trimr package?
#Jon: Yeah, that's a very good idea

#need to reformat data for trimr
data.trimr <- too.fast.gone %>%
  select(participant, posture, switchTrialType, congruentTrialType, reactionTime, correct_bin) %>%
  unite("condition", posture:congruentTrialType) %>%
  rename(rt = reactionTime, accuracy = correct_bin) %>%
  mutate(participant = as.factor(participant))
trimmingOutput.trimr <- modifiedRecursive(data.trimr, 
                                          minRT = .100,
                                          returnType = "mean", 
                                          digits = 4)
#this goes ahead and generates means (change returnType to "raw" to see trimmed raw data)


trimmingOutput = pjRecursiveTrim2(dataSet = too.fast.gone,
                                  dv = "reactionTime",
                                  splitvars = c("participant",
                                                "posture",
                                                "switchTrialType",
                                                "congruentTrialType"))
trimmedData=trimmingOutput[[1]]
totalN = trimmingOutput[[2]]
rejected = trimmingOutput[[3]]
percentTrimmed = trimmingOutput[[4]] #this is very close to the percentage trimmed for stroop
#2.14% of trials
percentTrimmed

Ncells = trimmingOutput[[5]] # 51 participants * 8 conditions

#now use trimmedData for same analyses as above

trimmed_rt_mean <- trimmedData %>%
  group_by(participant, 
           posture,
           congruentTrialType, 
           switchTrialType) %>%
  summarize(mean_rt    = mean(reactionTime))

##compare these means with means from trimr
a <- trimmed_rt_mean %>% 
  mutate(condition = paste(posture, switchTrialType, congruentTrialType, sep = "_"))
b <- trimmingOutput.trimr %>%
  pivot_longer(standing_noswitch_incongruent:sitting_noswitch_incongruent, 
               names_to = "condition", 
               values_to = "rt")
combined <- merge(a,b)
differences <- combined$mean_rt - combined$rt
hist(differences)

#Convert data to wide format 
trimmed_rt_mean_wide <- trimmed_rt_mean %>%
  pivot_wider(names_from = c(posture, 
                             congruentTrialType,
                             switchTrialType), 
              values_from =   mean_rt)

trimmed_RT_plot <- 
  superbPlot(trimmed_rt_mean_wide,
             WSFactors = c("Condition(2)", "Congruent(2)", "Posture(2)"),
             variables = colnames(ts_acc_mean_wide)[2:9],
             errorbar = "SE",
             plotStyle = "line",
             factorOrder = c("Condition","Posture","Congruent"),
             adjustments = list(purpose = "difference"))+
  theme_classic()+
  facet_wrap(vars(Congruent), labeller = labeller(Congruent = congruent.labs)) +
  scale_x_discrete(labels=c("1" = "No Switch", "2" = "Switch"))+
  scale_color_manual(values=c("#E69F00", "#0072B2"), labels = c("Sitting", "Standing")) +
  ylim(0.50, 0.70) +
  labs(y = "Reaction Time (seconds)")

ggsave(trimmed_RT_plot, 
       file = "plots/trimmed_RT_plot.pdf", 
       units = "in",
       width = 6.62, 
       height = 5.50,
       dpi = 600)

trimmed_RT_plot

exp1_anova_trimmed_rt <- ezANOVA(trimmed_rt_mean, 
                                 dv = mean_rt, 
                                 wid = participant, 
                                 within = .(posture, congruentTrialType, switchTrialType), 
                                 type = 3, 
                                 detailed = TRUE,
                                 return_aov = T
)

exp1_anova_trimmed_rt2 <- aov_ez(data = trimmed_rt_mean, 
                                 dv = 'mean_rt', 
                                 id = 'participant', 
                                 within = c('posture', 'congruentTrialType', 'switchTrialType'), 
                                 type = 3
)

exp1_stats_trimmed_rt <- ezStats(trimmed_rt_mean, 
                                 dv = mean_rt, 
                                 wid = participant, 
                                 within = .(posture, congruentTrialType, switchTrialType), 
                                 type = 3
)
write.csv(exp1_stats_trimmed_rt[ ,-7], 
          file = "output/Task_Switching_Descriptives_trimmed_RT.csv", 
          row.names = F)

#data.frame(exp1_anova$ANOVA)
output_trimmed_rt <- aovEffectSize(exp1_anova_trimmed_rt, effectSize = "pes")
output_trimmed_rt <- data.frame(output_trimmed_rt$ANOVA) %>%
  mutate(MSE = c(NA, exp1_anova_trimmed_rt2$anova_table$MSE), .before = F)
write.csv(output_trimmed_rt, "output/Task_switching_ANOVA_trimmed_RT.csv")
output_trimmed_rt


```


## Reproduce ANOVA for Smith et al. task-switching data
```{r}
#load acc data
Smith_Exp2_acc <- read_excel("Smith Data/StandingData.xlsx", 
                             sheet = "Exp2Acc")

head(Smith_Exp2_acc)

#Drop last row with comment
Smith_Exp2_acc <- Smith_Exp2_acc[1:30,]

#Restructure from wide to narrow, using tidyr
Smith_exp2_acc_narrow <- Smith_Exp2_acc %>%
  gather(v, accuracy, colnames(Smith_Exp2_acc)[2:9]) %>%
  separate(v, c("posture", "con", "switch")) %>%
  arrange(subj)


Smith_exp2_acc_anova <- ezANOVA(Smith_exp2_acc_narrow,
                                dv = accuracy,
                                wid = subj,
                                within = .(posture, con, switch),
                                type = 3,
                                detailed = TRUE,
                                return_aov=F
)

Smith_exp2_acc_anova

output_Smith_exp2_acc <- aovEffectSize(Smith_exp2_acc_anova, effectSize = "pes")
output_Smith_exp2_acc <- data.frame(output_Smith_exp2_acc$ANOVA)
write.csv(output_Smith_exp2_acc, "output/Smith_Exp2_ANOVA_acc.csv")
output_Smith_exp2_acc

#plot acc effect sizes for our results and Smith together
#Check that ANOVA tables (rows) match
output_acc$Effect
output_Smith_exp2_acc$Effect

ts.acc.pes <- data.frame(matrix(nrow = 8, ncol = 3))
ts.acc.pes[1] <- output_acc$Effect
ts.acc.pes[2] <- output_acc$pes
ts.acc.pes[3] <- output_Smith_exp2_acc$pes
ts.acc.pes[4] <- c(rep("Black", times = 5), "Red", "Black", "Black")

colnames(ts.acc.pes) <- c("Effect", "Current", "Original", "col")
#Scatter plot of original vs. reo effects

ggplot(ts.acc.pes, aes(x = Original, y = Current, colour = col)) +
  geom_point() + 
  geom_smooth(method = lm, se = T) + #Confidence interval is cutoff b/c values are bounded from 0 to 1
  scale_colour_identity() +
  xlim(-0.01, 1.01) +
  ylim(-0.01, 1.01)

# plot(ts.acc.pes$Current[2:8], 
#      ts.acc.pes$Original[2:8])
# lines(x = c(0,1), y = c(0,1))

#Exact proportion of current to original effect: ~9%
ts.acc.pes$Current[6]/ts.acc.pes$Original[6]

#Compare current vs. original effect sizes
interaction.original <- 
  get.ci.partial.eta.squared(output_Smith_exp2_acc$F[6], 
                             output_Smith_exp2_acc$DFn[6],
                             output_Smith_exp2_acc$DFd[6],
                             conf.level = 0.90) #Typical convention for partial-eta 


#Posture x congruency interaction
rep.exp1.peta2 <- 0.002  #Approx
rep.exp1.CI <- 
  get.ci.partial.eta.squared(0.081, 
                             2,
                             98,
                             conf.level = 0.90) 

Smith.exp1.peta2 <- 0.27
Smith.exp1.CI <- 
  get.ci.partial.eta.squared(4.73, 
                             2,
                             26,
                             conf.level = 0.90) 

#Posture x set size interaction
rep.exp3.peta2 <- 0.001 #Approx
rep.exp3.CI <- 
  get.ci.partial.eta.squared(0.031, 
                             1,
                             49,
                             conf.level = 0.90) 

Smith.exp3.peta2 <- 0.35
Smith.exp3.CI <- 
  get.ci.partial.eta.squared(1, 
                             11,
                             5.90,
                             conf.level = 0.90) 


ts.acc.pes.int <- data.frame(matrix(nrow = 6, ncol = 6))
colnames(ts.acc.pes.int) <- c("Data", "Type", "Effect.size", "CI.Lower", "CI.Upper", "name")
ts.acc.pes.int[6] <- c(rep("Exp 1", times = 2),
                       rep("Exp 2", times = 2),
                       rep("Exp 3", times = 2)
                       )

ts.acc.pes.int[2] <- rep(c("Replication", "Original"), times = 3)
# ts.acc.pes.int[6]     <- c(rep("RT1", times = 2),
#                            rep("Acc", times = 2),
#                            rep("RT2", times = 2)
#                           )

ts.acc.pes.int[1,3:5] <- c(rep.exp1.peta2, data.frame(rep.exp1.CI))
ts.acc.pes.int[2,3:5] <- c(Smith.exp1.peta2, data.frame(Smith.exp1.CI))
ts.acc.pes.int[3,3:5] <- c(ts.acc.pes$Current[6], data.frame(interaction_effect_CI))
ts.acc.pes.int[4,3:5] <- c(ts.acc.pes$Original[6], data.frame(interaction.original))
ts.acc.pes.int[5,3:5] <- c(rep.exp3.peta2, data.frame(rep.exp3.CI))
ts.acc.pes.int[6,3:5] <- c(Smith.exp3.peta2, data.frame(Smith.exp3.CI))

#Graph comparison of key effects for all three experiments- Similar to forest plot in sig
#filtering paper? 
forest.colors <- c("red", "black")

ts.acc.pes.int$Data <- as.factor(ts.acc.pes.int$Data)
ts.acc.pes.int$Type <- as.factor(ts.acc.pes.int$Type)

str(ts.acc.pes.int)
forest.comp <- mod.forestplot(df = ts.acc.pes.int,
                              estimate = Effect.size,
                              ci.lower = CI.Lower,
                              ci.upper = CI.Upper,
                              colour = Type,
                              xlab = "Partial Eta-Squared"
) + 
  scale_color_manual(values = forest.colors) 

forest.comp

#For a mini-meta-analysis
# Extracting (sampling) var or SE from PES? CIs around PES are calculated in papers and software using the lower and upper-bound F-ratio dfs
# Probably not possible (unknown sampling distribution)  
# https://www.google.com/books/edition/The_SAGE_Encyclopedia_of_Research_Design/Pn1ZEAAAQBAJ?hl=en&gbpv=1&dq=partial%20eta%20squared%20and%20sampling%20distribution&pg=PA1166&printsec=frontcover
# Convert to Cohen's d, one appropriate for a within design?
# Use dz? easystats

# Straub et al. used dav (Mdiff/Saverage), Cummings (2014) then corrected dz using Hedges gz
# For N > 20+ I think dz and gz are equvialent. Need to look up 
# https://easystats.github.io/effectsize/reference/t_to_r.html

# Comparison among all calculations
# https://www.tqmp.org/RegularArticles/vol17-1/p051/p051.pdf


```
